# @Author: 
# @Date:   2020-10-04T17:30:26-07:00
# @Last modified by:  
# @Last modified time: 2020-10-21T14:18:39-07:00



title: Data Science UCSB
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: blue
header:
  title: Data Science UCSB
  logo_img: images/datasciencelogotransparent.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Who We Are
      url: /who-we-are
    - label: Events Calendar
      url: /events-calendar
    - label: Blog
      url: /blog
    - label: Resources
      url: /resources
    - label: Mentorhsip Tip
      url: /mentorship
      #label: Intern Officer
     # url: https://docs.google.com/forms/d/1vWtewlfzzzT7B1YWUEhJNbNcDbdiK0qhN12Hm_TlS4Q/edit
     # new_window: true
    - label: FAQs
      url: /faqs
    - label: Connect
      url: https://docs.google.com/forms/d/e/1FAIpQLScSwEzUavR3oEyXwSRg9UViMGBJTBm_2FSJBf4GjGDqDmWI3A/viewform
      primary: true
      new_window: true
footer:
  logo_img: images/DataScienceSmallLogo.png
  tagline: datascience.ucsb@gmail.com
  has_nav: true
  nav_title: Company
  nav_links:
    - label: About Us
      url: /who-we-are
    - label: Blog
      url: /blog
    - label: connect
      url: https://docs.google.com/forms/d/e/1FAIpQLScSwEzUavR3oEyXwSRg9UViMGBJTBm_2FSJBf4GjGDqDmWI3A/viewform
      primary: true
      new_window: true
  
    - label: Email us
      url: 'mailto:datascience.ucsb@gmail.com'
  has_social: true
  social_title: Community
  social_links:
    - label: Instagram
      url: 'https://www.instagram.com/datascienceucsb/'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/company/data-science-at-ucsb'
      new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/DataScienceUCSB/'
      new_window: true
  has_subscribe: false
  content: '&copy; Stackbit. All rights reserved.'
  links:
    - label: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
